### ISSUE TITLE
Feature request: Clickable links should work when the name of the link is different to the target tiddler

### ISSUE THREAD

**Issue by grooveboxunited** [Gk0Wk/TW5-CodeMirror-Enhanced#20]
Currently clicking on links like `[[name of link|My tiddler]]` will open a tiddler called `name of link|My tiddler`.

It would be great if CodeMirror Enhanced would match the default TiddlyWiki behaviour in this case and open `My tiddler`.

Thanks for your work on this great plugin.

**Comment by Gk0Wk** [comment]
Good idea! I will rewrite the clickable links method after the new parse mode.
