### ISSUE TITLE
Feature request: Autocomplete for CamelCase links

### ISSUE THREAD

**Issue by grooveboxunited** [Gk0Wk/TW5-CodeMirror-Enhanced#21]
Would be great if autocomplete worked with CamelCase links without requiring the `[[` syntax.

**Comment by linonetwo** [comment]
CJK users don't really need this, so I think this can be in middle priority?

But I think it is not difficult to add it! So PR is welcome!

**Comment by linonetwo** [comment]
![截屏2021-11-21 22 01 28](https://user-images.githubusercontent.com/3746270/142764924-9416ec8b-1498-4cf0-b4f1-bd00e88ed493.png)

Maybe CJK user need this too

**Comment by Gk0Wk** [comment]
Thank you, that sounds interesting. But Scan the CamelCase words every time may cause lags and affect the writing experience. I can try this idea later, but it is not of the highest priority. If you really wang this feature, you can write a hint addon like [hint-tw5-tiddler.js](https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced/blob/main/src/addon/hint/hint-tw5-tiddler.js).

**Comment by linonetwo** [comment]
Not support in the core, for performance consideration.
