### ISSUE TITLE
TypeError: value.toString is not a function

### ISSUE THREAD

**Issue by ittayd** [Gk0Wk/TW5-CodeMirror-Enhanced#31]
I've installed the plugin. I also have the 'external attachments' plugin, not sure if it matters.
When I drag an image from a web page and import, an Untitled tiddler is created. After that, I start getting an exception as in the title. It happens in the function exports.getFieldString in $:/core/modules/widgets/jsontiddler.js at the last line (the 'else' section).
The field is 'fields' and it is a json object with no toString method. It tries to get this field from $:/plugins/Gk0Wk/TW5-CodeMirror-Enhanced/config.json.

**Comment by linonetwo** [comment]
maybe your cme plugin is broken, its `$:/plugins/Gk0Wk/TW5-CodeMirror-Enhanced/config.json` is incomplete, you can try reinstall it.

**Comment by ittayd** [comment]
This happens on a shared install and has happened to me several times. For some reason, after I drag the image, there is a field named 'fields' that is added to config.json and TW cannot handle it.

**Comment by ittayd** [comment]
Here is a file where the bug manifested itself. It doesn't happen if TCE is not installed
[error.zip](https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced/files/8752145/error.zip)

**Comment by linonetwo** [comment]
I see your debug log in Jermolene/TiddlyWiki5#6704 , this maybe a core bug, or maybe usage of jsontiddler in cme is wrong.

**Comment by cdaven** [comment]
As a workaround, I deleted my configuration by deleting the tiddler `$:/plugins/Gk0Wk/TW5-CodeMirror-Enhanced/config.json`. Seems to work.

**Comment by kookma** [comment]
Installing on a fresh empty.html + codemirror plugins raised this issue for me!
 I used the workaround by @cdaven

**Comment by ittayd** [comment]
Just mentioning this is still happening. Deleting of the configuration file solves the exception, but resets the configuration as well.

**Comment by zezehihi** [comment]
演示站也有这个问题。

**Comment by Gk0Wk** [comment]
have attempted to fix this issue in version 0.1.3.

**Comment by ittayd** [comment]
Seems to work. However, I now see the plugin overrides my theme (i have a dark theme and now the editor is white). How can I disable this?

**Comment by ittayd** [comment]
Works
