### ISSUE TITLE
Change Setting Checkboxes Do Not Work

### ISSUE THREAD

**Issue by kookma** [Gk0Wk/TW5-CodeMirror-Enhanced#34]
![img_030_msedge](https://user-images.githubusercontent.com/830394/191680183-7e84dc1d-75bb-411c-9545-c9a9d4235c13.gif)

**Comment by kookma** [comment]
Windows 10 + Chrome 105 + TW 5.2.3

**Comment by patrolli** [comment]
same issue

**Comment by linonetwo** [comment]
Seems fixed in latest release
