### ISSUE TITLE
Change The Config Brings Up RWD

### ISSUE THREAD

**Issue by kookma** [Gk0Wk/TW5-CodeMirror-Enhanced#35]
Any change to $:/plugins/Gk0Wk/TW5-CodeMirror-Enhanced/config.json brings up the Red Windows of Death

![img_032_msedge](https://user-images.githubusercontent.com/830394/191680721-25780b18-8335-4b17-9a2a-e861540d2046.gif)

See also https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced/issues/31

**Comment by kookma** [comment]
Any update for this!

**Comment by ouyangyexin** [comment]
我遇到了同样的问题，如果点击插件的配置按钮，不会有任何反应；如果直接修改插件的配置文件，会导致 tiddlywiki 内部错误。目前只有 语言是可以配置的。代码补全、可点击的连接、补全实时预览均不可配置。

**Comment by linonetwo** [comment]
什么居然已经被 sttot 修过了吗？那我发布个新版

**Comment by linonetwo** [comment]
我没权限发布，sttot 发布了
