### ISSUE TITLE
[BUG] 开头两行以及最后两行等异常

### ISSUE THREAD

**Issue by Zacharia2** [Gk0Wk/TW5-CodeMirror-Enhanced#37]
1. 缩进的问题，具体表现为编辑时的缩进与显示的缩进不一致导致的代码缩进混乱。可能是codemirror的设置中。

2. 两个斜杠后面的预览解释不正确。具体表现是，‘//’后面的所有文字都会显示斜体，并且两个斜杠后的内容不会预览。'/////' 五个斜杠包围的内容才会被正确预览。较为复杂，需要区分注释与斜体。

3. codemirror某个插件在删除最后两行时会报错。

**Comment by Zacharia2** [comment]
4. 开头一行使用快捷键以及编辑栏工具设置一级标题会导致开头两行都设置一级标题。并且无论设置二级标题还是列表，都会使开头两行设置他们。

![image](https://user-images.githubusercontent.com/32425955/210481868-189fe741-cb44-44ba-9009-3f6a6b032013.png)

**Comment by Zacharia2** [comment]
haedlinebreak.ts 文件名拼写错误，应为HardLineBreak

**Comment by linonetwo** [comment]
@Zacharia2 

> codemirror某个插件在删除最后两行时会报错。

这是啥意思

**Comment by linonetwo** [comment]
>     开头一行使用快捷键以及编辑栏工具设置一级标题会导致开头两行都设置一级标题。并且无论设置二级标题还是列表，都会使开头两行设置他们。

这个我也老遇到，但是应该原版 codemirror 就有吧？

**Comment by Zacharia2** [comment]
> 

就是选中最后两行然后按删除键就会出错。（应该是这样，毕竟隔了好久了）

**Comment by Zacharia2** [comment]
> 这个我也老遇到，但是应该原版 codemirror 就有吧？

原版倒是没试过哈。

**Comment by linonetwo** [comment]
一般按 tab ，在 codemirror  里添加的是两个空格吧，而不是制表符吧

**Comment by Zacharia2** [comment]
哦哦，就感觉从vscode复制粘贴的和自己在tw中写的看着差不多，vscode复制过去的很好看，自己在tw写的编辑时候看着好，显示很乱

**Comment by Zacharia2** [comment]
@linonetwo 这是对比图。缩进异常。

![image](https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced/assets/32425955/9aa56ba6-7318-4d76-a4cd-b1b2b210c38e)

![image](https://github.com/Gk0Wk/TW5-CodeMirror-Enhanced/assets/32425955/81ac26fc-100f-49f0-8bf2-2c8a7292c04e)

**Comment by linonetwo** [comment]
缩进那个估计是 codemirror 把 tab 和两个空格设成了一样长度，但是显示时没有这样

**Comment by Zacharia2** [comment]
明白了。
