### ISSUE TITLE
可以修改为中文的顿号或者其他符号来显示内容吗？英文的反斜杠要切换输入法，有点麻烦

### ISSUE THREAD

**Issue by dongrentianyu** [Gk0Wk/TW5-CodeMirror-Enhanced#38]
可以修改为中文的顿号或者其他符号来显示内容吗？英文的反斜杠要切换输入法，有点麻烦

希望可以由用户自定义，国外用户就保持原样，国内用户就手动设置一下。默认设置可以是顿号或者其他符号。不然这个功能总感觉用不上的样子。

**Comment by linonetwo** [comment]
其实我还想支持 ！ 中文感叹号，但是 codemirror 太老了，还是搞所见即所得吧

**Comment by dongrentianyu** [comment]
感觉就是很鸡肋，我感觉使用群体不明确，是给程序员用的还是给一般人使用的？我觉得应该严格区分两者，如果是给程序员用的，那就搭配的功能以程序员用的为主。如果是给普通用户用的，那就应该更多考虑普通用户的使用方式。

之前可能是给程序员用的，但现在普通用户也有这方面的需求了，所以或许应该调研一下，然后整合原有的功能，重要做一个插件来实现。

比较困难的就是像既是程序员，又需要跟普通用户一样的需求，就比较麻烦，两者不能有冲突才好。

也不知道codemirror复杂不复杂，回头技术提升了，再试试能不能搞一搞。
