### ISSUE TITLE
TypeError: value.toString is not a function

### ISSUE THREAD

**Issue by hffqyd** [Gk0Wk/TW5-CodeMirror-Enhanced#40]
In the example web [https://gk0wk.github.io/TW5-CodeMirror-Enhanced/](https://gk0wk.github.io/TW5-CodeMirror-Enhanced/), if click `save changes`, "Internal JavaScript error" showed, even if there is no changes.

![2023-02-10 19 16 37](https://user-images.githubusercontent.com/10190817/218079631-9946306a-a6e4-48d2-9d59-a98f9674bf4d.png)

**Comment by Gk0Wk** [comment]
have attempted to fix this issue in version 0.1.3.
